---
- name: Install Nginx
  dnf:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy custom index page
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: nginx
    group: nginx
    mode: '0644'

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
